### PR TITLE
F/alias typo

### PR DESCRIPTION
**Pull request by patriksvensson**
Fixed an alias typo i discovered when creating PR #1.

### CODE REVIEW

**Comment by SharpeRAD** [comment]
Sorry I should have accepted this PR instead.

**Comment by patriksvensson** [comment]
Should I resynchonize it against master?

**Comment by SharpeRAD** [comment]
Sorry I applied the changes in another commit. I need to brush up on my git skills as I'm still not comfortable in the shell.

**Comment by patriksvensson** [comment]
Should I close this PR?

**Comment by SharpeRAD** [comment]
If you can tell me how to sync it I'll give it ago?

**Comment by patriksvensson** [comment]
Since the change in this PR already is applied, there is no point of keeping it so I'm closing it :smile:

**Pull request closed without merging**
